#!/bin/bash

files=`ls *.js`
C=`pwd`

if [ ! -d "$HOME/.js" ]
then
  mkdir "$HOME/.js"
fi

for f in ${files[*]}
do
  p=$HOME/.js/${f}
  if [ ! -e $p ]
  then
    rm $p
    ln -s ${C}/${f} $p
  fi
done
